package com.tobias.leetcode.string;


/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class S_389FindTheDifference {


    public char findTheDifference(String s, String t) {

        int sSum = 0;
        int tSum = 0;
        for (int i = 0; i < s.length(); i++) {
            sSum += s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            tSum += t.charAt(i);
        }
        return (char)Math.abs(sSum - tSum);
    }

    public char findTheDifferenceByCount(String s, String t) {

        int length = Math.max(s.length(), t.length());
        int[] count = new int[26];
        for (int i = 0; i < length; i++) {
            if (i < s.length()) {
                count[s.charAt(i) - 'a']++;
            }
            if (i < t.length()) {
                count[t.charAt(i) - 'a']--;
            }
        }

        for (int i = 0; i < count.length; i++) {
            if (count[i] != 0) {
                return (char) (i + 'a');
            }
        }
        return ' ';
    }

    public static void main(String[] args) {
        S_389FindTheDifference findTheDifference = new S_389FindTheDifference();
        System.out.println(findTheDifference.findTheDifference("abcd",  "abcde"));
    }
}
